# Generated by Django 4.2.11 on 2026-04-08 02:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('property_type', models.CharField(choices=[('guesthouse', 'Guest House'), ('villa', 'Villa'), ('boutique_hotel', 'Boutique Hotel'), ('apartment', 'Apartment'), ('resort', 'Resort')], max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Sri Lanka', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('gallery_images', models.JSONField(default=list, help_text='Array of image URLs')),
                ('amenities', models.JSONField(default=list, help_text='Array of amenity strings')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0, help_text='Average rating 0-5')),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='tenants.owner')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('deluxe', 'Deluxe'), ('family', 'Family'), ('suite', 'Suite')], max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('beds', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('base_price_lkr', models.DecimalField(decimal_places=2, help_text='Base nightly rate in LKR', max_digits=12)),
                ('gallery_images', models.JSONField(default=list, help_text='Array of image URLs')),
                ('amenities', models.JSONField(default=list, help_text='Room-specific amenities')),
                ('is_available', models.BooleanField(default=True)),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('max_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_lkr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('season_type', models.CharField(choices=[('peak', 'Peak Season'), ('low', 'Low Season'), ('holiday', 'Holiday'), ('custom', 'Custom')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='properties.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Seasonal Pricing',
                'verbose_name_plural': 'Seasonal Pricing',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['tenant', 'start_date', 'end_date'], name='properties__tenant__d672f7_idx'), models.Index(fields=['room'], name='properties__room_id_9383d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('booked', 'Booked'), ('maintenance', 'Maintenance'), ('blocked', 'Manually Blocked'), ('unavailable', 'Unavailable')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_availability', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availability',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='properties__tenant__8d3ea1_idx'), models.Index(fields=['room', 'date'], name='properties__room_id_3cd436_idx')],
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'is_available'], name='properties__tenant__48425b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property'], name='properties__propert_81b02f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property', 'name')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'is_published'], name='properties__tenant__b0cf34_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
    ]
